### ISSUE TITLE
Unable to use appnext

### ISSUE THREAD

**Issue by flure** [britzl/defads#1]
I've set up a small app accordingly to the instructions, for testing purposes. 
Whenever I post the message `"show_video"` or `"show_interstitial"` to appnext, it doesn't work and I get the following output in the console :

```
ERROR:SCRIPT: defads/shared/util.lua:26: attempt to concatenate a nil value
stack traceback:
	defads/shared/util.lua:26: in function 'iac_url'
	defads/appnext/appnext.lua:122: in function 'video'
	defads/appnext/appnext.script:38: in function <defads/appnext/appnext.script:11>
```
Note that I didn't try using defads with any other network yet.

**Comment by britzl** [comment]
This project has been deprecated and replaced by Defold native extension support for FGL Enhance, AdMob, Unity Ads and others. Please refer to the Asset Portal: https://www.defold.com/community/assets/
